jobs:
- job: ${{ parameters.name }}
  steps:
  - template: docker_steps.yml
    parameters:
      DOCKER_IMAGE: ${{ parameters.DOCKER_IMAGE }}
  - script: ./scripts/run_tests_CI.sh "${TEST_GLOB}"
    displayName: 'Run test'
    env:
      TEST_GLOB: ${{ parameters.env }}
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
